// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwl4EzWz9Bq1D_1NH8nxK7vFoMCluuK_w',
    appId: '1:725344943703:web:c0791ec87e340e0bde6d12',
    messagingSenderId: '725344943703',
    projectId: 'loadspotter',
    authDomain: 'loadspotter.firebaseapp.com',
    storageBucket: 'loadspotter.appspot.com',
    measurementId: 'G-LK3SKG7QSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATbQS-ksIfwtyyQrfr9r8VL5NLeLknrXc',
    appId: '1:725344943703:android:611d2aa06ee0b70bde6d12',
    messagingSenderId: '725344943703',
    projectId: 'loadspotter',
    storageBucket: 'loadspotter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpODoR73WgeCPCxXEvAIG9fDON-WGqfQY',
    appId: '1:725344943703:ios:8064891973fd9c4fde6d12',
    messagingSenderId: '725344943703',
    projectId: 'loadspotter',
    storageBucket: 'loadspotter.appspot.com',
    iosBundleId: 'com.example.loadspotter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpODoR73WgeCPCxXEvAIG9fDON-WGqfQY',
    appId: '1:725344943703:ios:8064891973fd9c4fde6d12',
    messagingSenderId: '725344943703',
    projectId: 'loadspotter',
    storageBucket: 'loadspotter.appspot.com',
    iosBundleId: 'com.example.loadspotter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwl4EzWz9Bq1D_1NH8nxK7vFoMCluuK_w',
    appId: '1:725344943703:web:863fa93159186a13de6d12',
    messagingSenderId: '725344943703',
    projectId: 'loadspotter',
    authDomain: 'loadspotter.firebaseapp.com',
    storageBucket: 'loadspotter.appspot.com',
    measurementId: 'G-1ERF6QWKNX',
  );
}
